/*
 * IDENTIFICATION:
 * stub generated Mon May  6 10:39:06 2019
 * with a MiG generated by bootstrap_cmds-96.20.2.200.4
 * OPTIONS: 
 */

/* Module kextmanager_reply */

#define	__MIG_check__Request__kextmanager_reply_subsystem__ 1

#include <string.h>
#include <mach/ndr.h>
#include <mach/boolean.h>
#include <mach/kern_return.h>
#include <mach/notify.h>
#include <mach/mach_types.h>
#include <mach/message.h>
#include <mach/mig_errors.h>
#include <mach/port.h>
	
/* BEGIN VOUCHER CODE */

#ifndef KERNEL
#if defined(__has_include)
#if __has_include(<mach/mig_voucher_support.h>)
#ifndef USING_VOUCHERS
#define USING_VOUCHERS
#endif
#ifndef __VOUCHER_FORWARD_TYPE_DECLS__
#define __VOUCHER_FORWARD_TYPE_DECLS__
#ifdef __cplusplus
extern "C" {
#endif
	extern boolean_t voucher_mach_msg_set(mach_msg_header_t *msg) __attribute__((weak_import));
#ifdef __cplusplus
}
#endif
#endif // __VOUCHER_FORWARD_TYPE_DECLS__
#endif // __has_include(<mach/mach_voucher_types.h>)
#endif // __has_include
#endif // !KERNEL
	
/* END VOUCHER CODE */

	
/* BEGIN MIG_STRNCPY_ZEROFILL CODE */

#if defined(__has_include)
#if __has_include(<mach/mig_strncpy_zerofill_support.h>)
#ifndef USING_MIG_STRNCPY_ZEROFILL
#define USING_MIG_STRNCPY_ZEROFILL
#endif
#ifndef __MIG_STRNCPY_ZEROFILL_FORWARD_TYPE_DECLS__
#define __MIG_STRNCPY_ZEROFILL_FORWARD_TYPE_DECLS__
#ifdef __cplusplus
extern "C" {
#endif
	extern int mig_strncpy_zerofill(char *dest, const char *src, int len) __attribute__((weak_import));
#ifdef __cplusplus
}
#endif
#endif /* __MIG_STRNCPY_ZEROFILL_FORWARD_TYPE_DECLS__ */
#endif /* __has_include(<mach/mig_strncpy_zerofill_support.h>) */
#endif /* __has_include */
	
/* END MIG_STRNCPY_ZEROFILL CODE */


#include <mach/std_types.h>
#include <mach/mig.h>
#include <mach/mig.h>
#include <mach/mach_types.h>
#include <IOKit/kext/kextmanager_types.h>

#ifndef	mig_internal
#define	mig_internal	static __inline__
#endif	/* mig_internal */

#ifndef	mig_external
#define mig_external
#endif	/* mig_external */

#if	!defined(__MigTypeCheck) && defined(TypeCheck)
#define	__MigTypeCheck		TypeCheck	/* Legacy setting */
#endif	/* !defined(__MigTypeCheck) */

#if	!defined(__MigKernelSpecificCode) && defined(_MIG_KERNEL_SPECIFIC_CODE_)
#define	__MigKernelSpecificCode	_MIG_KERNEL_SPECIFIC_CODE_	/* Legacy setting */
#endif	/* !defined(__MigKernelSpecificCode) */

#ifndef	LimitCheck
#define	LimitCheck 0
#endif	/* LimitCheck */

#ifndef	min
#define	min(a,b)  ( ((a) < (b))? (a): (b) )
#endif	/* min */

#if !defined(_WALIGN_)
#define _WALIGN_(x) (((x) + 3) & ~3)
#endif /* !defined(_WALIGN_) */

#if !defined(_WALIGNSZ_)
#define _WALIGNSZ_(x) _WALIGN_(sizeof(x))
#endif /* !defined(_WALIGNSZ_) */

#ifndef	UseStaticTemplates
#define	UseStaticTemplates	0
#endif	/* UseStaticTemplates */

#ifndef	__DeclareRcvRpc
#define	__DeclareRcvRpc(_NUM_, _NAME_)
#endif	/* __DeclareRcvRpc */

#ifndef	__BeforeRcvRpc
#define	__BeforeRcvRpc(_NUM_, _NAME_)
#endif	/* __BeforeRcvRpc */

#ifndef	__AfterRcvRpc
#define	__AfterRcvRpc(_NUM_, _NAME_)
#endif	/* __AfterRcvRpc */

#ifndef	__DeclareRcvSimple
#define	__DeclareRcvSimple(_NUM_, _NAME_)
#endif	/* __DeclareRcvSimple */

#ifndef	__BeforeRcvSimple
#define	__BeforeRcvSimple(_NUM_, _NAME_)
#endif	/* __BeforeRcvSimple */

#ifndef	__AfterRcvSimple
#define	__AfterRcvSimple(_NUM_, _NAME_)
#endif	/* __AfterRcvSimple */

#define novalue void

#define msgh_request_port	msgh_local_port
#define MACH_MSGH_BITS_REQUEST(bits)	MACH_MSGH_BITS_LOCAL(bits)
#define msgh_reply_port		msgh_remote_port
#define MACH_MSGH_BITS_REPLY(bits)	MACH_MSGH_BITS_REMOTE(bits)

#define MIG_RETURN_ERROR(X, code)	{\
				((mig_reply_error_t *)X)->RetCode = code;\
				((mig_reply_error_t *)X)->NDR = NDR_record;\
				return;\
				}

/* typedefs for all requests */

#ifndef __Request__kextmanager_reply_subsystem__defined
#define __Request__kextmanager_reply_subsystem__defined

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t rval;
		mountpoint_t busyVol;
		char busyVolPad[2];
		int busyStatus;
	} __Request__lock_reboot_reply_t __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t rval;
		int lockStatus;
	} __Request__lock_volume_reply_t __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack()
#endif
#endif /* !__Request__kextmanager_reply_subsystem__defined */

/* typedefs for all replies */

#ifndef __Reply__kextmanager_reply_subsystem__defined
#define __Reply__kextmanager_reply_subsystem__defined

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t RetCode;
	} __Reply__lock_reboot_reply_t __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t RetCode;
	} __Reply__lock_volume_reply_t __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack()
#endif
#endif /* !__Reply__kextmanager_reply_subsystem__defined */


/* union of all replies */

#ifndef __ReplyUnion__kextmanager_reply_subsystem__defined
#define __ReplyUnion__kextmanager_reply_subsystem__defined
union __ReplyUnion__kextmanager_reply_subsystem {
	__Reply__lock_reboot_reply_t Reply_lock_reboot_reply;
	__Reply__lock_volume_reply_t Reply_lock_volume_reply;
};
#endif /* __RequestUnion__kextmanager_reply_subsystem__defined */
/* Forward Declarations */


mig_internal novalue _Xlock_reboot_reply
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xlock_volume_reply
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);


#if ( __MigTypeCheck )
#if __MIG_check__Request__kextmanager_reply_subsystem__
#if !defined(__MIG_check__Request__lock_reboot_reply_t__defined)
#define __MIG_check__Request__lock_reboot_reply_t__defined

mig_internal kern_return_t __MIG_check__Request__lock_reboot_reply_t(__attribute__((__unused__)) __Request__lock_reboot_reply_t *In0P)
{

	typedef __Request__lock_reboot_reply_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__lock_reboot_reply_t__defined) */
#endif /* __MIG_check__Request__kextmanager_reply_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* SimpleRoutine lock_reboot_reply */
#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
kern_return_t lock_reboot_reply
(
	mach_port_t replyPart,
	kern_return_t rval,
	mountpoint_t busyVol,
	int busyStatus
);

/* SimpleRoutine lock_reboot_reply */
mig_internal novalue _Xlock_reboot_reply
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t rval;
		mountpoint_t busyVol;
		char busyVolPad[2];
		int busyStatus;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__lock_reboot_reply_t __Request;
	typedef __Reply__lock_reboot_reply_t Reply __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__lock_reboot_reply_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__lock_reboot_reply_t__defined */

	__DeclareRcvSimple(70106, "lock_reboot_reply")
	__BeforeRcvSimple(70106, "lock_reboot_reply")

#if	defined(__MIG_check__Request__lock_reboot_reply_t__defined)
	check_result = __MIG_check__Request__lock_reboot_reply_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__lock_reboot_reply_t__defined) */

	OutP->RetCode = lock_reboot_reply(In0P->Head.msgh_request_port, rval, In0P->busyVol, In0P->busyStatus);
	__AfterRcvSimple(70106, "lock_reboot_reply")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__kextmanager_reply_subsystem__
#if !defined(__MIG_check__Request__lock_volume_reply_t__defined)
#define __MIG_check__Request__lock_volume_reply_t__defined

mig_internal kern_return_t __MIG_check__Request__lock_volume_reply_t(__attribute__((__unused__)) __Request__lock_volume_reply_t *In0P)
{

	typedef __Request__lock_volume_reply_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__lock_volume_reply_t__defined) */
#endif /* __MIG_check__Request__kextmanager_reply_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* SimpleRoutine lock_volume_reply */
#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
kern_return_t lock_volume_reply
(
	mach_port_t replyPart,
	kern_return_t rval,
	int lockStatus
);

/* SimpleRoutine lock_volume_reply */
mig_internal novalue _Xlock_volume_reply
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t rval;
		int lockStatus;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__lock_volume_reply_t __Request;
	typedef __Reply__lock_volume_reply_t Reply __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__lock_volume_reply_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__lock_volume_reply_t__defined */

	__DeclareRcvSimple(70107, "lock_volume_reply")
	__BeforeRcvSimple(70107, "lock_volume_reply")

#if	defined(__MIG_check__Request__lock_volume_reply_t__defined)
	check_result = __MIG_check__Request__lock_volume_reply_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__lock_volume_reply_t__defined) */

	OutP->RetCode = lock_volume_reply(In0P->Head.msgh_request_port, rval, In0P->lockStatus);
	__AfterRcvSimple(70107, "lock_volume_reply")
}


#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
boolean_t kextmanager_reply_server(
		mach_msg_header_t *InHeadP,
		mach_msg_header_t *OutHeadP);

#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
mig_routine_t kextmanager_reply_server_routine(
		mach_msg_header_t *InHeadP);


/* Description of this subsystem, for use in direct RPC */
const struct kextmanager_reply_subsystem {
	mig_server_routine_t 	server;	/* Server routine */
	mach_msg_id_t	start;	/* Min routine number */
	mach_msg_id_t	end;	/* Max routine number + 1 */
	unsigned int	maxsize;	/* Max msg size */
	vm_address_t	reserved;	/* Reserved */
	struct routine_descriptor	/*Array of routine descriptors */
		routine[8];
} kextmanager_reply_subsystem = {
	kextmanager_reply_server_routine,
	70100,
	70108,
	(mach_msg_size_t)sizeof(union __ReplyUnion__kextmanager_reply_subsystem),
	(vm_address_t)0,
	{
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xlock_reboot_reply, 4, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__lock_reboot_reply_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xlock_volume_reply, 3, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__lock_volume_reply_t)},
	}
};

mig_external boolean_t kextmanager_reply_server
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{
	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	register mig_routine_t routine;

	OutHeadP->msgh_bits = MACH_MSGH_BITS(MACH_MSGH_BITS_REPLY(InHeadP->msgh_bits), 0);
	OutHeadP->msgh_remote_port = InHeadP->msgh_reply_port;
	/* Minimal size: routine() will update it if different */
	OutHeadP->msgh_size = (mach_msg_size_t)sizeof(mig_reply_error_t);
	OutHeadP->msgh_local_port = MACH_PORT_NULL;
	OutHeadP->msgh_id = InHeadP->msgh_id + 100;
	OutHeadP->msgh_reserved = 0;

	if ((InHeadP->msgh_id > 70107) || (InHeadP->msgh_id < 70100) ||
	    ((routine = kextmanager_reply_subsystem.routine[InHeadP->msgh_id - 70100].stub_routine) == 0)) {
		((mig_reply_error_t *)OutHeadP)->NDR = NDR_record;
		((mig_reply_error_t *)OutHeadP)->RetCode = MIG_BAD_ID;
		return FALSE;
	}
	(*routine) (InHeadP, OutHeadP);
	return TRUE;
}

mig_external mig_routine_t kextmanager_reply_server_routine
	(mach_msg_header_t *InHeadP)
{
	register int msgh_id;

	msgh_id = InHeadP->msgh_id - 70100;

	if ((msgh_id > 7) || (msgh_id < 0))
		return 0;

	return kextmanager_reply_subsystem.routine[msgh_id].stub_routine;
}
